# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c97ab435d63786b9b2f70a90570585da064244d124a9558f9f2d3f308f93371070b8a1d6ded89db671cb1d94c4ed0ebac4db3c5487c3ad70616ddad3da5cdd6

test:
  secret_key_base: 35664e63e0f9037b6480196329fa194560e6b9096fb7a0ea4875897cbdd2add008dcfc4411fa45963ad0e8214a35502366b6c74db54d56ce9f2729d0527602f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
